#!/bin/bash

# change domain
domain="example.com"

liveDir="/etc/acme.sh/live"
cert="${liveDir}/${domain}/cert.pem"
key="${liveDir}/${domain}/privkey.pem"

scriptUrl="https://github.com/orgcontrib/omv-scripts/raw/main/update_cert.sh"
scriptPath="/usr/local/sbin/update_cert.sh"

if [ ! -f "${scriptPath}" ]; then
  wget -O ${scriptPath} ${scriptUrl}
  chmod +x ${scriptPath}
fi

${scriptPath} "" ${cert} ${key} "acme.sh"

exit 0
